### ISSUE TITLE
执行browserify lib/index.js > dist/xss.js -s xss   之后报错

### ISSUE THREAD

**Issue by DaYuXiaoZhangTaiHou** [leizongmin/js-xss#145]
Error: Cannot find module 'cssfilter' from 'E:\myspace\js-xss\lib'
    at C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:46:17
    at process (C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:173:43)
    at ondir (C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:188:17)
    at load (C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:69:43)
    at onex (C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:92:31)
    at C:\Users\31251\AppData\Roaming\npm\node_modules\browserify\node_modules\_resolve@1.1.7@resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by DaYuXiaoZhangTaiHou** [comment]
已解决
